const { MessageButton } = require("discord-buttons");
const disbutpages = require("discord-embeds-pages-buttons")
const color = process.env.Color;
module.exports = {
    name: 'images',
    cooldown: 5,
    permissions: ["SEND_MESSAGES"],
    clientpermissions: ["SEND_MESSAGES", "EMBED_LINKS"],
    async execute(client, message, cmd, args, Discord) {
        message.react('📷');
        const embed15 = new Discord.MessageEmbed().setThumbnail(client.user.displayAvatarURL()).setTimestamp().setColor(`${color}`).setDescription('**`📸 Images (40)`** \n[ad](https://xopbot.glitch.me/) \n**You Became A `AD`** \n[pet](https://xopbot.glitch.me/) \n**Aww You Got `Pat`** \n[m&m](https://xopbot.glitch.me/) \n**Wow You Are A `M&M`** \n[phub](https://xopbot.glitch.me/) \n**Why\'re You On `PHUB?`** \n[drip](https://xopbot.glitch.me/) \n**Im Freaking `Drippy`**').setFooter(`Created By: ${message.author.tag}`, message.author.displayAvatarURL())
        const embed16 = new Discord.MessageEmbed().setThumbnail(client.user.displayAvatarURL()).setTimestamp().setColor(`${color}`).setDescription('**`📸 Images (40)`** \n[alert](https://xopbot.glitch.me/) \n**Alert The `World`** \n[facts](https://xopbot.glitch.me/) \n**Only True `Facts`** \n[clown](https://xopbot.glitch.me/) \n**You\'re Truly A `Clown`** \n[drake](https://xopbot.glitch.me/) \n**The `Drake Meme`** \n[water](https://xopbot.glitch.me/) \n**I Need Water, `HELP ME`**').setFooter(`Created By: ${message.author.tag}`, message.author.displayAvatarURL())
        const embed17 = new Discord.MessageEmbed().setThumbnail(client.user.displayAvatarURL()).setTimestamp().setColor(`${color}`).setDescription('**`📸 Images (40)`** \n[clyde](https://xopbot.glitch.me/) \n**Clyde Is `Typing...`** \n[biden](https://xopbot.glitch.me/) \n**I\'m The `President`**  \n[grave](https://xopbot.glitch.me/) \n**No I `Died R.I.P`** \n[stonks](https://xopbot.glitch.me/) \n**Wow I\'m `Rich ASF`** \n[heaven](https://xopbot.glitch.me/) \n**OMG Its So `Nice`**').setFooter(`Created By: ${message.author.tag}`, message.author.displayAvatarURL())
        const embed18 = new Discord.MessageEmbed().setThumbnail(client.user.displayAvatarURL()).setTimestamp().setColor(`${color}`).setDescription('**`📸 Images (40)`** \n[pikachu](https://xopbot.glitch.me/) \n**The `Pikachu Meme`** \n[uncover](https://xopbot.glitch.me/) \n**The `Rick&Morty Meme`** \n[iamspeed](https://xopbot.glitch.me/) \n**I\'m `Fast Asf Boi`** \n[rickroll](https://xopbot.glitch.me/) \n**LOL Get `Rickrolled`** \n[tableflip](https://xopbot.glitch.me/) \n**I Lost. `Great!`**').setFooter(`Created By: ${message.author.tag}`, message.author.displayAvatarURL())
        const embed19 = new Discord.MessageEmbed().setThumbnail(client.user.displayAvatarURL()).setTimestamp().setColor(`${color}`).setDescription('**`📸 Images (40)`** \n[fbiopenup](https://xopbot.glitch.me/) \n**FBI Is Here, `Run`** \n[batmanslap](https://xopbot.glitch.me/) \n**Why `Slap XOPBOT?`** \n[carreverse](https://xopbot.glitch.me/) \n**The `Cringe Is Too Much`** \n[wideavatar](https://xopbot.glitch.me/) \n**Why My `PFP Wide?`** \n[dockofshame](https://xopbot.glitch.me/) \n**Losers, `Outta Here!`**').setFooter(`Created By: ${message.author.tag}`, message.author.displayAvatarURL())
        const embed20 = new Discord.MessageEmbed().setThumbnail(client.user.displayAvatarURL()).setTimestamp().setColor(`${color}`).setDescription('**`📸 Images (40)`** \n[opinion](https://xopbot.glitch.me/) \n**That\'s My `Opinion`** \n[wanted](https://xopbot.glitch.me/) \n**Oh, `I\'m Wanted`** \n[simp](https://xopbot.glitch.me/) \n**I Became A `Simp`** \n[gun](https://xopbot.glitch.me/) \n**What Did You `Say?!`** \n[changemymind](https://xopbot.glitch.me/) \n**Change Anyones `Mind`**').setFooter(`Created By: ${message.author.tag}`, message.author.displayAvatarURL())
        const embed21 = new Discord.MessageEmbed().setThumbnail(client.user.displayAvatarURL()).setTimestamp().setColor(`${color}`).setDescription('**`📸 Images (40)`** \n[triggered](https://xopbot.glitch.me/) \n**A `Triggered User`** \n[hitler](https://xopbot.glitch.me/) \n**You `Evil Monster`** \n[wasted](https://xopbot.glitch.me/) \n**I `Wasted Myself`** \n[trash](https://xopbot.glitch.me/) \n**You `Trash User`** \n[facepalm](https://xopbot.glitch.me/) \n**Just Why? `Why!`**').setFooter(`Created By: ${message.author.tag}`, message.author.displayAvatarURL())
        const embed22 = new Discord.MessageEmbed().setThumbnail(client.user.displayAvatarURL()).setTimestamp().setColor(`${color}`).setDescription('**`📸 Images (40)`** \n[noaffectbaby](https://xopbot.glitch.me/) \n**Don\'t Affect The `Baby`** \n[monster](https://xopbot.glitch.me/) \n**OMG, `Hideous&Scary`** \n[blur](https://xopbot.glitch.me/) \n**Disgusting, `Blur It`** \n[jail](https://xopbot.glitch.me/) \n**Mum Pay My `Bail :(`** \n[spank](https://xopbot.glitch.me/) \n**You\'ve Been `Bad`**').setFooter(`Created By: ${message.author.tag}`, message.author.displayAvatarURL())
        const pages = [embed15, embed16, embed17, embed18, embed19, embed20, embed21, embed22]
        disbutpages.pages(message, pages, { timeout: 540 * 1000, buttons: { delete: { style: "red", emoji: "❌", text: "Delete" }, forward: { style: "blurple", emoji: "⏩", text: "Forward" }, backward: { style: "blurple", emoji: "⏪", text: "Backward" } }, extraRows: [], extraPos: "below", message: "", ephemeral: "**Button Failure! Reasons: \n1.`Not Your Embed!`\n2.`Buttons Timed OUT!`**", })
    }
}